#!/bin/bash
# LumenShake Quick Reference Card
# Print this for quick access during operations

echo "=========================================="
echo "  LUMENSHAKE QUICK REFERENCE CARD"
echo "=========================================="
echo ""
echo "📊 HEALTH CHECKS"
echo "  curl http://localhost:4000/health"
echo "  curl http://localhost:4000/api/cache/stats"
echo "  curl http://localhost:4000/metrics"
echo ""
echo "🚀 START/STOP"
echo "  Start: cd backend && node src/index.js > server.log 2>&1 &"
echo "  Stop:  pkill -f 'node src/index.js'"
echo "  Worker: node src/worker.js > worker.log 2>&1 &"
echo ""
echo "📈 LOAD TESTING"
echo "  Full test: node load-test.js"
echo "  Quick test: npx autocannon -c 30 -d 10 http://localhost:4000/health"
echo "  API test: ./test-api-responses.sh"
echo ""
echo "🔧 MAINTENANCE"
echo "  Clear cache: curl -X POST http://localhost:4000/api/cache/clear"
echo "  View logs: tail -f logs/app.log"
echo "  View errors: tail -f logs/error.log"
echo "  DB backup: pg_dump -U postgres lumenshake > backup.sql"
echo ""
echo "🎯 PERFORMANCE TARGETS"
echo "  P99 Latency: < 100ms (Current: 40-60ms ✅)"
echo "  Throughput: > 1000 req/s (Current: 1400-2000+ ✅)"
echo "  Cache Hit: > 70% (Current: 70-90% ✅)"
echo "  DB Pool: < 80% (Current: 5-30/50 ✅)"
echo ""
echo "📚 DOCUMENTATION"
echo "  Operations: docs/OPERATIONS_RUNBOOK.md"
echo "  Incidents: docs/INCIDENT_RESPONSE_RUNBOOK.md"
echo "  Performance: docs/PERFORMANCE_TUNING_GUIDE.md"
echo "  Summary: docs/PERFORMANCE_OPTIMIZATION_SUMMARY.md"
echo ""
echo "🚨 EMERGENCY COMMANDS"
echo "  Restart: pkill -f 'node src/index.js' && node src/index.js > server.log 2>&1 &"
echo "  DB kill: psql -U postgres -c 'SELECT pg_terminate_backend(pid) FROM pg_stat_activity;'"
echo "  Check OOM: dmesg | grep -i 'killed process'"
echo "  Memory: ps aux | grep node | awk '{print \$4, \$6}'"
echo ""
echo "=========================================="
echo "  OPTIMIZED FOR 30+ CONCURRENT USERS ✅"
echo "=========================================="
